# Generated by Django 5.1.1 on 2024-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
