# Generated by Django 5.1.1 on 2024-10-21 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_userprofile_website_url_userprofile_urls_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='email_id',
        ),
    ]
